Repository facebookexperimental/object-introspection, pull requests merged in 2023-12, with the labels that each got.

#426 Integration Tests: Fix thrift_unions tests
  test/integration/thrift_unions.toml
Labels: cla signed

#427 CodeGen: Remove Incomplete members from Classes
  oi/type_graph/RemoveMembers.cpp
  test/test_remove_members.cpp
Labels: cla signed, priority

#430 Really, really make sure arrays when used as a template parameter have a name
  oi/OICodeGen.cpp
Labels: cla signed

#431 Type Graph: Replace MutationTracker with the more general ResultTracker
  oi/type_graph/IdentifyContainers.cpp
  oi/type_graph/IdentifyContainers.h
  oi/type_graph/NodeTracker.h
  oi/type_graph/Types.cpp
  oi/type_graph/Types.h
  oi/type_graph/Visitor.h
Labels: cla signed

#376 ci: move formatting checks to nix
  .circleci/config.yml
  flake.lock
  flake.nix
Labels: cla signed

#385 capture_keys: store dynamic type path components more efficiently
  include/oi/IntrospectionResult.h
  oi/IntrospectionResult.cpp
Labels: cla signed

#433 OID: Make CodeGen v2 (TypeGraph) the default
  .circleci/config.yml
  oi/OID.cpp
Labels: cla signed

#432 NameGen: Override inputName for anonymous members
  oi/type_graph/NameGen.cpp
  test/integration/anonymous.toml
  test/test_name_gen.cpp
Labels: cla signed

#420 TypeGraph: Fix handling for classes which inherit from containers
  oi/CodeGen.cpp
  oi/type_graph/AlignmentCalc.cpp
  oi/type_graph/AlignmentCalc.h
  oi/type_graph/DrgnParser.h
  oi/type_graph/Flattener.cpp
  oi/type_graph/Flattener.h
  oi/type_graph/IdentifyContainers.cpp
  oi/type_graph/IdentifyContainers.h
  oi/type_graph/Printer.cpp
  oi/type_graph/Printer.h
  oi/type_graph/Prune.cpp
  oi/type_graph/Prune.h
  oi/type_graph/TypeIdentifier.cpp
  oi/type_graph/Types.h
  oi/type_graph/Visitor.h
  test/TypeGraphParser.cpp
  test/TypeGraphParser.h
  test/test_add_children.cpp
  test/test_alignment_calc.cpp
  test/test_codegen.cpp
  test/test_flattener.cpp
  test/test_identify_containers.cpp
  test/test_prune.cpp
  test/test_type_identifier.cpp
  test/type_graph_utils.cpp
Labels: cla signed

#425 CodeGen v2: Enable independent running without CodeGen v1
  oi/CodeGen.cpp
  oi/CodeGen.h
  oi/ContainerInfo.cpp
  oi/OIDebugger.cpp
  oi/type_graph/CMakeLists.txt
  oi/type_graph/DrgnExporter.cpp
  oi/type_graph/DrgnExporter.h
  oi/type_graph/EnforceCompatibility.cpp
  oi/type_graph/Types.cpp
  oi/type_graph/Types.h
  test/integration/alignment.toml
  test/integration/anonymous.toml
  test/integration/cycles.toml
  test/integration/ignored.toml
  test/integration/inheritance_multiple.toml
  test/integration/namespaces.toml
  test/integration/pointers_incomplete.toml
  test/integration/std_conditional.toml
  test/integration/std_deque_del_allocator.toml
  test/integration/std_list_del_allocator.toml
  test/integration/std_priority_queue.toml
  test/integration/std_queue.toml
  test/integration/std_stack.toml
  test/integration/std_variant.toml
  test/integration/std_vector_del_allocator.toml
  test/integration/templates.toml
  test/integration/typedefs.toml
  test/test_enforce_compatibility.cpp
Labels: cla signed

#435 codegen: remove reliance on drgn type for top level name
  oi/CodeGen.cpp
  oi/CodeGen.h
Labels: cla signed

#421 oilgen: migrate to source parsing
  CMakeLists.txt
  oi/CodeGen.cpp
  oi/CodeGen.h
  oi/OIGenerator.cpp
  oi/OIGenerator.h
  oi/type_graph/CMakeLists.txt
  oi/type_graph/ClangTypeParser.cpp
  oi/type_graph/ClangTypeParser.h
  oi/type_graph/DrgnExporter.cpp
  oi/type_graph/DrgnExporter.h
  oi/type_graph/NameGen.cpp
  oi/type_graph/NameGen.h
  oi/type_graph/Printer.cpp
  oi/type_graph/Printer.h
  oi/type_graph/RemoveTopLevelPointer.cpp
  oi/type_graph/RemoveTopLevelPointer.h
  oi/type_graph/Types.h
  oi/type_graph/Visitor.h
  tools/OILGen.cpp
  types/string_type.toml
Labels: cla signed, fb-exported

#437 tbv2: implement folly::IOBuf
  types/folly_iobuf_type.toml
Labels: cla signed

#441 clangparser: mark incomplete arrays as incomplete without failing
  oi/type_graph/ClangTypeParser.cpp
Labels: cla signed
