Repository facebookexperimental/object-introspection, pull requests merged in 2023-08, with the labels that each got.

#274 CI: Set installs to noninteractive so they don't hang waiting for user input
  .circleci/config.yml
Labels: cla signed

#272 TypeGraph: Set alignment for Thrift isset container to 1
  oi/type_graph/Types.h
Labels: cla signed

#273 AlignmentCalc: Mark as packed if members are not aligned
  oi/type_graph/AlignmentCalc.cpp
  test/test_alignment_calc.cpp
Labels: cla signed

#230 Flattener: Handle incomplete parent types
  oi/type_graph/Flattener.cpp
  test/test_flattener.cpp
Labels: cla signed

#277 OIRP: Add copyright header
  tools/OIRP.cpp
Labels: cla signed

#265 TopoSorterTest: Add test for value template params
  test/test_topo_sorter.cpp
Labels: cla signed

#264 TypeGraph: Change Type::name() to return a reference instead of a copy
  oi/type_graph/NameGen.cpp
  oi/type_graph/NameGen.h
  oi/type_graph/Types.cpp
  oi/type_graph/Types.h
Labels: cla signed

#275 Printer: Use NodeIds for stable IDs when printing graphs
  oi/type_graph/PassManager.cpp
  oi/type_graph/Printer.cpp
  oi/type_graph/Printer.h
  oi/type_graph/TypeGraph.cpp
  oi/type_graph/TypeGraph.h
  test/test_add_children.cpp
  test/test_codegen.cpp
  test/test_drgn_parser.cpp
  test/test_flattener.cpp
  test/test_remove_top_level_pointer.cpp
  test/test_type_identifier.cpp
  test/type_graph_utils.cpp
  test/type_graph_utils.h
Labels: cla signed

#290 Workaround for #289 missing symbol
  types/try_type.toml
Labels: cla signed

#287 DrgnParser: store type of template param value
  oi/type_graph/DrgnParser.cpp
  oi/type_graph/Flattener.cpp
  oi/type_graph/NameGen.cpp
  oi/type_graph/Printer.cpp
  oi/type_graph/TypeIdentifier.cpp
  oi/type_graph/Types.h
  test/TypeGraphParser.cpp
  test/test_drgn_parser.cpp
  test/test_flattener.cpp
  test/test_name_gen.cpp
  test/test_prune.cpp
  test/test_topo_sorter.cpp
Labels: cla signed, priority

#288 TypeGraph: Add option to record enumerator names
  oi/CodeGen.cpp
  oi/type_graph/DrgnParser.cpp
  oi/type_graph/DrgnParser.h
  oi/type_graph/Printer.cpp
  oi/type_graph/Printer.h
  oi/type_graph/Types.h
  test/integration/enums.toml
  test/test_add_children.cpp
  test/test_drgn_parser.cpp
  test/test_drgn_parser.h
Labels: cla signed

#282 type_graph: provide inputName for all types
  oi/type_graph/AddPadding.cpp
  oi/type_graph/NameGen.cpp
  oi/type_graph/Printer.cpp
  oi/type_graph/TypeIdentifier.cpp
  oi/type_graph/Types.h
  test/TypeGraphParser.cpp
  test/test_codegen.cpp
  test/test_name_gen.cpp
  test/test_type_identifier.cpp
Labels: cla signed, priority

#319 Fix JIT CodeGen for Try<…>
  types/try_type.toml
Labels: cla signed

#323 std::set implementation for Container V2
  test/integration/std_set_custom_comparator.toml
  types/set_type.toml
Labels: cla signed

#324 Update internal build for oil v2
  include/oi/oi-jit.h
  include/oi/oi.h
Labels: cla signed

#325 oil: fix verbosity level in jit oil
  oi/CodeGen.cpp
  oi/OILibraryImpl.cpp
Labels: cla signed

#327 name contained types properly in treebuilder v2
  oi/CodeGen.cpp
  oi/OITraceCode.cpp
  oi/type_graph/Printer.cpp
  oi/type_graph/TopoSorter.cpp
  oi/type_graph/TopoSorter.h
  oi/type_graph/TypeIdentifier.cpp
  oi/type_graph/TypeIdentifier.h
  oi/type_graph/Types.h
  test/TypeGraphParser.cpp
  test/test_codegen.cpp
  test/test_name_gen.cpp
  test/test_topo_sorter.cpp
  test/test_type_identifier.cpp
  types/array_type.toml
  types/map_seq_type.toml
  types/multi_map_type.toml
  types/multi_set_type.toml
  types/pair_type.toml
  types/seq_type.toml
  types/set_type.toml
  types/std_map_type.toml
Labels: cla signed

#330 tbv2: add make_field helper
  oi/CodeGen.cpp
  types/array_type.toml
  types/map_seq_type.toml
  types/multi_map_type.toml
  types/multi_set_type.toml
  types/pair_type.toml
  types/seq_type.toml
  types/set_type.toml
  types/std_map_type.toml
Labels: cla signed

#332 Compile Time OIL for OIL v2
  include/ObjectIntrospection.h
  include/oi/oi.h
  oi/CodeGen.cpp
  oi/CodeGen.h
  oi/FuncGen.cpp
  oi/FuncGen.h
  oi/Headers.h
  oi/OICompiler.cpp
  oi/OIGenerator.cpp
  oi/OIGenerator.h
  resources/CMakeLists.txt
Labels: cla signed

#333 Fix double parseVarint for ParsedData::Sum
  oi/exporters/ParsedData.cpp
Labels: bug, cla signed, types, library
