Repository facebookexperimental/object-introspection, pull requests merged in 2023-09, with the labels that each got.

#341 json: fix bug where a past the end iterator would be dereferenced
  oi/exporters/Json.cpp
Labels: cla signed, fb-exported

#344 oil: update iterator for range based for loops
  include/oi/IntrospectionResult-inl.h
  include/oi/IntrospectionResult.h
Labels: cla signed

#342 Update to clang/llvm 15
  .circleci/config.yml
  CMakeLists.txt
  oi/OICodeGen.cpp
  oi/OICompiler.cpp
  oi/OICompiler.h
  oi/OIGenerator.cpp
  oi/OIGenerator.h
  oi/type_graph/AddChildren.cpp
  test/ci.oid.toml
  test/integration/alignment.toml
  test/integration_mttest.cpp
  test/integration_sleepy.cpp
  tools/OILGen.cpp
Labels: cla signed, fb-exported

#345 oil: change std::stack reference to a std::function
  include/oi/exporters/inst.h
  oi/CodeGen.cpp
  oi/FuncGen.cpp
  oi/IntrospectionResult.cpp
  types/array_type.toml
  types/f14_fast_map.toml
  types/f14_fast_set.toml
  types/f14_node_map.toml
  types/f14_node_set.toml
  types/f14_value_map.toml
  types/f14_value_set.toml
  types/f14_vector_map.toml
  types/f14_vector_set.toml
  types/map_seq_type.toml
  types/multi_map_type.toml
  types/multi_set_type.toml
  types/optional_type.toml
  types/pair_type.toml
  types/seq_type.toml
  types/set_type.toml
  types/shrd_ptr_type.toml
  types/small_vec_type.toml
  types/std_map_type.toml
  types/std_unordered_map_type.toml
  types/std_unordered_multimap_type.toml
  types/uniq_ptr_type.toml
  types/unordered_multiset_type.toml
  types/unordered_set_type.toml
Labels: cla signed, fb-exported

#346 static types: add consume function similar to delegate
  include/oi/types/st.h
  oi/CodeGen.cpp
Labels: cla signed

#348 oilgen: add debug flag
  tools/OILGen.cpp
Labels: cla signed

#347 oilgen: hash linkage names in output path
  oi/OIGenerator.cpp
Labels: cla signed

#351 DrgnParser: Options should default to false
  oi/type_graph/DrgnParser.h
  test/test_drgn_parser.cpp
  test/test_drgn_parser.h
Labels: cla signed

#354 oilgen: avoid demangling empty symbols
  oi/OIGenerator.cpp
Labels: cla signed

#352 oilgen: add missing gflags header
  tools/OILGen.cpp
Labels: cla signed

#353 codegen: generate enums as enum class
  oi/CodeGen.cpp
  test/integration/enums.toml
  test/test_drgn_parser.cpp
Labels: cla signed

#356 Printer: Make prefix() [[nodiscard]] and fix bug printing Dummy nodes
  oi/type_graph/Printer.cpp
  oi/type_graph/Printer.h
Labels: cla signed

#358 Use objectintrospection.org for the website
  README.md
  website/docusaurus.config.js
  website/static/CNAME
Labels: cla signed

#362 rocksdb: update to v8.5.3
  CMakeLists.txt
Labels: cla signed

#357 prevent name collision between uintptr_t and uint64_t
  oi/OITraceCode.cpp
  oi/type_graph/DrgnParser.cpp
  oi/type_graph/TypeGraph.cpp
  oi/type_graph/Types.cpp
  oi/type_graph/Types.h
  test/TypeGraphParser.cpp
  test/integration/std_pair.toml
  test/test_add_children.cpp
  test/test_drgn_parser.cpp
Labels: cla signed

#365 CodeGen: Store list of ContainerInfos in unique_ptrs for reference stability
  oi/CodeGen.cpp
  oi/CodeGen.h
  oi/type_graph/DrgnParser.cpp
  oi/type_graph/DrgnParser.h
  test/test_drgn_parser.cpp
Labels: cla signed, codegen

#367 jit logging: fix for codegen v1
  oi/CodeGen.cpp
  oi/FuncGen.cpp
  oi/FuncGen.h
  oi/OICodeGen.cpp
Labels: cla signed

#368 Implement Container V2 for fbstring
  .circleci/config.yml
  oi/OITraceCode.cpp
  test/integration/fbstring.toml
  types/fb_string_type.toml
Labels: cla signed

#369 Implement Container V2 for folly::sorted_vector_set
  test/integration/sorted_vector_set.toml
  types/sorted_vec_set_type.toml
Labels: cla signed

#349 Add CSV Exporter
  include/oi/exporters/CSV.h
  oi/CMakeLists.txt
  oi/exporters/CSV.cpp
Labels: cla signed, library

#372 folly::sorted_vector_map: Add key-capture support
  test/integration/capture_keys.toml
  types/map_seq_type.toml
Labels: cla signed
