Repository facebookexperimental/object-introspection, pull requests merged in 2024-01, with the labels that each got.

#447 circleci: clean up codegen v1 runs
  .circleci/config.yml
  test/test_add_children.cpp
Labels: cla signed

#448 tbv2: calculate total memory footprint
  include/oi/exporters/Json.h
  include/oi/result/SizedResult-inl.h
  include/oi/result/SizedResult.h
  oi/CMakeLists.txt
  oi/exporters/Json.cpp
  test/integration/CMakeLists.txt
  test/integration/anonymous.toml
  test/integration/arrays.toml
  test/integration/enums.toml
  test/integration/enums_params.toml
  test/integration/fbstring.toml
  test/integration/folly_f14_fast_map.toml
  test/integration/folly_f14_fast_set.toml
  test/integration/folly_f14_node_map.toml
  test/integration/folly_f14_node_set.toml
  test/integration/folly_f14_value_map.toml
  test/integration/folly_f14_value_set.toml
  test/integration/folly_f14_vector_map.toml
  test/integration/folly_f14_vector_set.toml
  test/integration/folly_small_vector.toml
  test/integration/folly_sorted_vector_map.toml
  test/integration/gen_tests.py
  test/integration/inheritance_access.toml
  test/integration/inheritance_multiple.toml
  test/integration/packed.toml
  test/integration/padding.toml
  test/integration/pointers.toml
  test/integration/primitives.toml
  test/integration/runner_common.cpp
  test/integration/simple.toml
  test/integration/sorted_vector_set.toml
  test/integration/std_list.toml
  test/integration/std_list_del_allocator.toml
  test/integration/std_map_custom_comparator.toml
  test/integration/std_multimap_custom_comparator.toml
  test/integration/std_multiset_custom_comparator.toml
  test/integration/std_optional.toml
  test/integration/std_pair.toml
  test/integration/std_set_custom_comparator.toml
  test/integration/std_smart_ptr.toml
  test/integration/std_unordered_map_custom_operator.toml
  test/integration/std_unordered_multimap_custom_operator.toml
  test/integration/std_unordered_multiset_custom_operator.toml
  test/integration/std_unordered_set_custom_operator.toml
  test/integration/std_vector.toml
  test/integration/std_vector_del_allocator.toml
  test/integration/templates.toml
  test/integration/thrift_unions.toml
  test/integration/typedefed_parent.toml
  test/integration/unions.toml
Labels: cla signed

#377 incomplete: name type in compiler errors
  oi/CodeGen.cpp
  oi/OITraceCode.cpp
  oi/type_graph/DrgnExporter.cpp
  oi/type_graph/NameGen.cpp
  oi/type_graph/NameGen.h
  oi/type_graph/Printer.cpp
  oi/type_graph/TopoSorter.cpp
  oi/type_graph/TopoSorter.h
  oi/type_graph/Types.cpp
  oi/type_graph/Types.h
  test/TypeGraphParser.cpp
  test/integration/pointers_incomplete.toml
  test/test_drgn_parser.cpp
  test/test_flattener.cpp
  test/test_name_gen.cpp
  test/test_remove_members.cpp
  types/shrd_ptr_type.toml
  types/uniq_ptr_type.toml
Labels: cla signed

#449 tbv2: fix type names for std::optional
  test/integration/std_optional.toml
  types/optional_type.toml
Labels: cla signed

#454 Add namespaces to integration tests' "typeName"
  test/integration/inheritance_polymorphic.toml
  test/integration/inheritance_polymorphic_diamond.toml
  test/integration/inheritance_polymorphic_non_dynamic_base.toml
  test/integration/thrift_unions.toml
Labels: cla signed, types, testing

#450 tbv2: update tuple test
  test/integration/std_tuple.toml
Labels: cla signed, testing

#455 tbv2: correctly account for list overhead
  test/integration/std_list.toml
  test/integration/std_list_del_allocator.toml
  types/cxx11_list_type.toml
  types/list_type.toml
Labels: cla signed

#456 tbv2: name array member types correctly
  oi/FuncGen.cpp
  oi/type_graph/TopoSorter.cpp
  oi/type_graph/TopoSorter.h
  test/integration/arrays.toml
  test/test_topo_sorter.cpp
Labels: cla signed

#452 tbv2: add is_primitive to output
  include/oi/exporters/Json.h
  include/oi/exporters/inst.h
  include/oi/result/Element.h
  oi/CodeGen.cpp
  oi/FuncGen.cpp
  oi/IntrospectionResult.cpp
  test/integration/simple.toml
  types/f14_fast_map.toml
  types/f14_node_map.toml
  types/f14_value_map.toml
  types/f14_vector_map.toml
  types/map_seq_type.toml
  types/multi_map_type.toml
  types/std_map_type.toml
  types/std_unordered_map_type.toml
  types/std_unordered_multimap_type.toml
Labels: cla signed

#460 test: add features field to integration tests
  test/integration/README.md
  test/integration/anonymous.toml
  test/integration/arrays.toml
  test/integration/bitfields.toml
  test/integration/cycles.toml
  test/integration/gen_tests.py
  test/integration/inheritance_polymorphic.toml
  test/integration/inheritance_polymorphic_diamond.toml
  test/integration/inheritance_polymorphic_non_dynamic_base.toml
  test/integration/pointers.toml
  test/integration/pointers_function.toml
  test/integration/pointers_incomplete.toml
  test/integration/std_smart_ptr.toml
  test/integration/thrift_isset.toml
  test/integration/thrift_isset_missing.toml
  test/integration/thrift_namespaces.toml
Labels: cla signed

#462 tbv2: support capture-thrift-isset
  include/oi/exporters/Json.h
  oi/CodeGen.cpp
  oi/OITraceCode.cpp
  oi/type_graph/ClangTypeParser.cpp
  oi/type_graph/DrgnParser.cpp
  oi/type_graph/Types.h
  test/integration/enums.toml
  test/integration/thrift_isset.toml
  test/integration/thrift_isset_missing.toml
Labels: cla signed

#463 tbv2: fix thrift isset with ClangTypeParser
  oi/type_graph/ClangTypeParser.cpp
Labels: cla signed

#461 tbv2: fix pointer codegen
  oi/CodeGen.cpp
  oi/FuncGen.cpp
  oi/FuncGen.h
  oi/type_graph/TopoSorter.cpp
  oi/type_graph/TopoSorter.h
  test/integration/anonymous.toml
  test/integration/pointers.toml
  test/integration/pointers_incomplete.toml
  test/test_topo_sorter.cpp
Labels: cla signed

#443 type_graph: avoid overwriting explicitly set alignment
  oi/type_graph/AlignmentCalc.cpp
  oi/type_graph/ClangTypeParser.cpp
Labels: cla signed

#464 tbv2: fix Thrift isset lookups with padding
  oi/CodeGen.cpp
  test/integration/thrift_isset.toml
Labels: cla signed

#467 Implement Container V2 for std::deque
  test/integration/std_deque.toml
  test/integration/std_deque_del_allocator.toml
  types/deque_list_type.toml
Labels: cla signed, types, codegen

#465 container_info: switch to boost::regex
  oi/CMakeLists.txt
  oi/ContainerInfo.cpp
  oi/ContainerInfo.h
  oi/OICodeGen.cpp
  oi/type_graph/ClangTypeParser.cpp
  oi/type_graph/IdentifyContainers.cpp
  oi/type_graph/TypeIdentifier.cpp
  test/test_container_info.cpp
Labels: cla signed, fb-exported

#469 fix string type sso computation
  oi/OITraceCode.cpp
  types/cxx11_string_type.toml
  types/fb_string_type.toml
  types/small_vec_type.toml
  types/string_type.toml
Labels: cla signed

#473 Make KeyCapture work with nested typedefs
  oi/CodeGen.cpp
  oi/type_graph/KeyCapture.cpp
  oi/type_graph/Printer.cpp
  oi/type_graph/TopoSorter.cpp
  oi/type_graph/Types.h
  oi/type_graph/Visitor.h
  test/integration/capture_keys.toml
  test/test_key_capture.cpp
Labels: cla signed

#442 tbv2: use std::decay_t with smart pointers
  oi/FuncGen.cpp
  test/integration/std_smart_ptr.toml
  types/shrd_ptr_type.toml
  types/uniq_ptr_type.toml
Labels: cla signed

#474 stub clang::BuiltinType::NullPtr primitive type
  oi/type_graph/ClangTypeParser.cpp
Labels: cla signed, fb-exported
